### ISSUE TITLE
Fetch messages since last messsage id

### ISSUE THREAD

**Issue by saazrai** [ddeboer/imap#119]
Is it possible to fetch messages more than a particular message id?

$mailbox->getMessages(where id > 1000).

If not how do I fetch only the latest messages?

**Comment by holdmann** [comment]
@saazrai Its a good question.

I already implemented this functionality using next algorythm:

First of all, I add new method to Message class

```php    
    /**
     * Returns status info about current mailbox.
     *
     * @return mixed
     */
    public function getStatus()
    {
        $this->init();

        return imap_status($this->connection->getResource(), $this->mailbox, \SA_ALL);
    }
```

This allows to get status information of mailbox, see http://php.net/manual/en/function.imap-status.php

Second one, i compare status->uidnext with already stored after previous execution.

And if current is more than stored i use getMessages() method with expression `SINCE 'date'`.

**Important**:

1. date in since operator doesn't sensetive to hours, minutes and seconds, so its like enough you should skip processing already processed messages;
2. varius imap servers support different set of expressions, so i used fetching scenarions: fullscan and default.

I hope it will be useful to someone.

**Comment by holdmann** [comment]
And here new exceprion if bad search expression occurs https://github.com/ddeboer/imap/pull/114/commits/8fc6e8893c61ba55d46319a9ab6a3b06489646ab

**Comment by Slamdunk** [comment]
Related to https://github.com/ddeboer/imap/pull/114

**Comment by Slamdunk** [comment]
Hi, to fetch the messages of last month you can use the `Since` search criteria:
```php
$today = new DateTimeImmutable();
$lastMonth = $today->sub(new DateInterval('P30D'));
$messages = $mailbox->getMessages(
    new Ddeboer\Imap\Search\Date\Since($lastMonth),
    \SORTDATE, // Sort criteria
    true  // Descending order
);
```
