### ISSUE TITLE
Directly access to part of message

### ISSUE THREAD

**Issue by wujku** [ddeboer/imap#229]
When I need to get contents of part like attachment, I do not need to load the entire message. 
Let's say I know it number and I would like to use `getDecodedContent()` method from `AbstractPart` class. 
Firstly, you should allow access to `getContentPartNumber` method for get part number outside class.

Do you have any suggestions how to solving this problem?

**Comment by Slamdunk** [comment]
When you get a Message, the only function that we have to call mandatorily is `imap_fetchstructure`, that doesn't load the entire message but only the structure (if by _loading_ you mean downloading).
Retrieving attachments and querying them never load the entire message.

If you intend to also skip the `imap_fetchstructure` call, well we can't: in the perspective of this library, how would you know the contet part number without `imap_fetchstructure`? This is an OOP library and skipping its API would make it less robust.

**Comment by wujku** [comment]
https://github.com/ddeboer/imap/blob/0bf18d890e4e10aa8d387bb6be413afd12260c68/src/Message/AbstractPart.php#L340
https://github.com/ddeboer/imap/blob/0bf18d890e4e10aa8d387bb6be413afd12260c68/src/Message/AbstractPart.php#L353
I suggest to set `$partNumber` as key of `$this->parts` element. Then I can extract the key from `getAttachments()` method. 

Below method should added to `AbstractMessage` class. 
```
    /**
     * @param $partNumber
     * @return Attachment|SimplePart
     */
    public function getPart($partNumber)
    {
        return $this->parts[$partNumber];
    }
```

@Slamdunk can i prepare pull request?

**Comment by Slamdunk** [comment]
Some considerations:

1. Either way we can expose the `$partNumber`, the entire message will always be entirely loaded, because each part is immediately loaded at object construction, and Message constructs every part in its contructor itself, so you'll never gain any performance if this is your purpose
1. Changing the key of the `$parts` array is a breaking change and would require a v2.0: that's not really an issue, but we are going to do this only if there's a reasonable purpose to pursue. Until now I still don't understand what's exactly your **use-case** purpose.
1. Nevertheless we can expose the `$partNumber` adding a `getPartNumber()` to `PartInterface`, so if you need a specific part you can iterate over all parts and get the only part you need:
    ```php
    foreach ($message->getParts() as $part) {
        if ($part->getPartNumber() === '1.2.1.3') {
            // do stuff
        }
    }
    ```
1. Leave `getContentPartNumber()` untouched: its solely purpose is for the EmbeddedMessages and has a slightly different meaning

If you still intend to open the PR please:
* mark AbstractPart::$partNumber as `private`
* move it one step down, between `$parts` and `$messageNumber`
* change subclasses references to use the new API only:
  * src/Message/EmbeddedMessage.php [61,74]
  * src/Message/Attachment.php [57,62]
