### ISSUE TITLE
How to get single messages with embed images

### ISSUE THREAD

**Issue by tasmanwebsolutions** [ddeboer/imap#275]
Hi not really issue but I am new to your php imap. Is there away to get single message by id and display them with attachments and embedded images etc.

To you have a proper user guide.

**Comment by Slamdunk** [comment]
> Is there away to get single message by id

It depends on what you mean by id. If you mean UID as defined by RFC 3501 (see https://tools.ietf.org/html/rfc3501#section-2.3.1.1) yes, simply retrieve the mailbox and then get the message:
```php
$message = $mailbox->getMessage($uid);
```
Instead if you mean Message-ID as defined by RFC 5322 (see https://tools.ietf.org/html/rfc5322#section-3.6.4) then no because it is not mandatory and does not have a standard, neither for setting it nor for searching by it.

> and display them with attachments and embedded images

Displaying messages is not within the purpose of this library.
