### ISSUE TITLE
Perfomance issue on $mailbox->getStatus()

### ISSUE THREAD

**Issue by rtwent** [ddeboer/imap#286]
Hi, thank You for Your wonderfull code - I've found some things that must be taught.
Despite good code style there are some perfomance issues.
For example code:
```php
$mailboxes = $connection->getMailboxes();
foreach ($mailboxes as $mailbox) {  
 $status = $mailbox->getStatus();  
}  
```
executes twice slowly then native php code or workaround code:
```php
$resourse = $connection->getResource()->getStream();
$mailboxes = $connection->getMailboxes();

foreach ($mailboxes as $mailbox) {  
 $status = \imap_status($resourse, $mailbox->getFullEncodedName(), \SA_ALL)  
}  
```
I can not deeply dive, because we spent a lot of days to understand that imap* functions in php have perfomance issues and neither squirell nor roundcube uses them. I just think that something wrong with **$this->resource->getStream()** but it always var_dump the same resource on iteration calls. So the problem not in the surface. Same slow behaviour was found while iterating messages in the mailbox, but I can not reproduce it here.  $headers = $message->getHeaders(); $headers->get('unseen') etc. works faster for me then Your get*() methods.
Your AbstractMessage::getAttachments() is WOW. Was it a big sense in such construction or it was just practical use of php features.
Thank You. Best regards

**Comment by Slamdunk** [comment]
Hi, thanks for the question.

> imap* functions in php have perfomance issues and neither squirell nor roundcube uses them

We found `ext-imap` to be somewhere incomplete and with performance issues too: we know other libraries do not use the extension and prefer to directly go with raw calls, but we do not want to go that way. This is and will always be an `ext-imap` OOP wrapper, nothing more, nothing less.
We are not intended, nor we have the time, to write raw calls as IMAP RFCs would state.

> I just think that something wrong with **$this->resource->getStream()**

The slowness is due to:
https://github.com/ddeboer/imap/blob/43e88f17f4c0ee57f06ddc4ad78b82a1132a8cc3/src/ImapResource.php#L77-L82
This code is executed between 1 and 2 times for **each** imap operation.
Why? Because the resource is tightened to the opened mailbox, and since this is an OOP library, you can operate in non-imperative way.
Take for example:
```php
$mailboxes = $connection->getMailboxes();

$mailboxes[0]->getMessage(1);
$mailboxes[1]->getMessage(1);

$mailboxes[0]->getMessage(2);
$mailboxes[1]->getMessage(2);
```
Without checking every time which is the opened mailbox, we could return the wrong message.
Or maybe you could also manually close the library resource, and everything would crash.

In the code-coverage you can see that this behaviour is mandatory for at least 14 tests in the test-suite:
https://scrutinizer-ci.com/g/ddeboer/imap/code-structure/master/code-coverage/src/ImapResource.php

**Comment by Slamdunk** [comment]
A performance enhancement was just release on [1.5.0](https://github.com/ddeboer/imap/releases/tag/1.5.0).
