### ISSUE TITLE
Subject is not decoding if it is not encoded correct

### ISSUE THREAD

**Issue by dkop** [ddeboer/imap#291]
If i have email with this header in CP1251:
```Subject: Незакодированная тема```
i can not get correctly decoded subject via method ```getSubject()```
Header is not encoded like here:
```Subject: =?windows-1251?B?zeXi4CDA4vLu6u7sIOfg6uDnIDEtMyDk7f8=?=```
Example eml is attached.
[aecp1251.eml.zip](https://github.com/ddeboer/imap/files/1657134/aecp1251.eml.zip)

**Comment by Slamdunk** [comment]
Hi, I think this case doesn't have a solution. The default charset can't be guessed, and you can't rely on the user default charset to expect the result you want.
For example, on an european clean Windows installation with default Thunderbird parameters I get:

![cp1251](https://user-images.githubusercontent.com/152236/35320465-2d91bdf0-00e4-11e8-90e9-83e588911b21.gif)

Instead if I replace the header with the encoded example you provided, everything looks good.

**Comment by dkop** [comment]
Yes, it is incorrect encoding on the sender side, but webmail of my email provider (https://mail.yandex.ru/) shows it correct.
![aescr](https://user-images.githubusercontent.com/980674/35329499-241946e4-0111-11e8-93a7-c803f40c0411.png)
The problem also is not in encoding itself, but postgres can not save to database string received with incorrect utf symbols
![pstgr](https://user-images.githubusercontent.com/980674/35329583-74fd44d4-0111-11e8-8d36-3cf339deae70.png)

**Comment by dkop** [comment]
I think if header is not encoded with mime/base64, it must be converted to utf8 when parsing it in Header.php. For example in my case charset can be detected or we can get it from content-type header of message text:
```
Content-Type: text/html; charset=windows-1251
Content-Transfer-Encoding: 8bit
```

**Comment by Slamdunk** [comment]
> Yes, it is incorrect encoding on the sender side, but webmail of my email provider (https://mail.yandex.ru/) shows it correct.

This means that yandex.ru has either (1) a charset guessing mechanism or (2) a default charset setting.
I am not aware of a reliable charset guessing mechanism, do you?
As far as I can see setting a default charset other than ASCII would be highly unreliable, since it's the RFC specified charset.

> The problem also is not in encoding itself, but postgres can not save to database string received with incorrect utf symbols

This doesn't seem an issue related to this library.

> we can get it from content-type header of message text:

In your case there is only one part, but what if there are multiple parts, each with different charset?
Still it would be an auto-guessing mechanism, and it would be a nightmare to write and maintain 😦
