### ISSUE TITLE
Copy sent mails to \Sent

### ISSUE THREAD

**Issue by soywod** [ddeboer/imap#323]
I have a custom SMTP / IMAP server (running on docker), and my aim is to build a PHP API to interact with this server. I'm using your lib to communicate with the IMAP part, and I use PHPMailer to send mails via this SMTP part. My question is : how can I copy the SMTP sent mail to the Sent IMAP mailbox ? I had in mind to create a new Message instance (I have the sent message ID from PHPMailer), transfert all properties to this new instance, then use the `copy()` method to the \Sent mailbox. Any doc, advices ?

EDIT: In fact, the question can be resumed this way : how to copy a mail that does not exist yet to a mailbox ?

**Comment by soywod** [comment]
I've found my answer, looking at the code : `Mailbox::addMessage`. Is it documented somewhere ? If not, it could be interesting to add some informations about this.

**Comment by Slamdunk** [comment]
Hi, the `MailboxInterface::addMessage()` method is a wrapper for the native [imap_append](https://secure.php.net/manual/en/function.imap-append.php) PHP function.

As you pointed out, there is no documentation for the method of this library, mainly because it is a trivial wrapper. If you are so kind to create a Pull Request that updates the README.md introduction few notes about this, we would appreciate it very much :+1:

**Comment by soywod** [comment]
I'll do so with great pleasure :)
